### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Elsensee** [phpbb-de/phpbb-ext-newsletter#1]
- [x] UCP setting has to be added
- [x] Must be posted in newsletter archive
- [ ] Link in email to unsubscribe without login (optional)
